### ISSUE TITLE
Installation on the BC store fails on first attempt

### ISSUE THREAD

**Issue by bc-ppuente** [hatertron3000/webhooks-manager#6] opened 2019-07-29 19:53 UTC
**Description**
----
The first time a user tries to install the app on a store, the user is not created in Cognito, though BC provided a token that gets stored in DynamoDB. Logs indicate the PreSignup lambda may be making multiple POST requests to login.bigcommerce.com/oauth2/token.

**Steps to Reproduce**
----
1. Complete the installation steps up to "Installing on the BigCommerce store"
2. Attempt to install the app on a store
3. Agree to the terms of service and click "Signup"

**Expected Result**
----
Signup is successful

**Actual Result**
----
Error message indicating signup failed. New row added to the table in DynamoDB, but no new user in Cognito.

Uninstalling the app from the BC store and attempting installation a 2nd time completes installation successfully.

**Comment by hatertron3000** [comment] 2019-07-30 02:42
The multiple calls are caused by Cognito's behavior of retrying the presignup lambda if it does not get a response in <5s.

See: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html

> Important
> Amazon Cognito invokes Lambda functions synchronously. When called, your Lambda function must respond within 5 seconds. If it does not, Amazon Cognito retries the call. After 3 unsuccessful attempts, the function times out. This 5-second timeout value cannot be changed.

Consider returning a promise immediately, then resolving or rejecting based on the response from BC. Example of returning a promise from Lambda here: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html

**Closed** 2019-07-30 03:45 UTC
Labels: bug
